### ISSUE TITLE
BFT & PoW

### ISSUE THREAD

**Issue by gleim** [cosmos/cosmos#18]
There is an opportunity to very briefly identify Tendermint as related to PBFT solutions (http://tendermint.com/blog/tendermint-vs-pbft/) and provide external academic references to blockchain network architectures intermixing BFT and PoW from that field of research (e.g., http://vukolic.com/iNetSec_2015.pdf).

From my understanding, this is a BFT/PoW/PoS network architecture.

If this understanding is correct, I would make this clarification in the motivation section that opens the paper.

Also, I think the external Vukolic reference provides valuable context for the reader.

If you agree, I'll make whichever changes and issue the pull request.

**Comment by gleim** [comment]
https://github.com/gnuclear/gnuclear-whitepaper/pull/19

**Comment by jaekwon** [comment]
Oh thanks, that's a great idea.  We'll find more to write about there I'm sure.
