### ISSUE TITLE
install the whole cosmos

### ISSUE THREAD

**Issue by rock1103** [cosmos/cosmos#69]
Hi:
can I install the whole cosmos with the code in github, do you have some  Installation document?

thank you.

**Comment by jolesbi** [comment]
hey @rock1103 
you should checkout https://github.com/cosmos/gaia

@nylira can we change this repo name to cosmos.github.io / cosmos website instead of cosmos?

**Comment by rigelrozanski** [comment]
Nope this repo is only for documentation, check out the `cosmos/cosmos-sdk`

**Comment by jolesbi** [comment]
we should consider calling this repo ‘/cosmos-docs’
