### ISSUE TITLE
Issue in setting up Validator

### ISSUE THREAD

**Issue by yassersheikh** [cosmos/cosmos#98]
Getting this error 

ERROR: checkTx failed: (65545) === ABCI Log ===
Codespace: 1
Code:      9
ABCICode:  65545
Error:     --= Error =--
Data: common.FmtError{format:"cosmosaccaddr1gv5vj5men6r8r73aywdzadafy9y06tvfwmvy                                                                                        fx", args:[]interface {}(nil)}
Msg Traces:
--= /Error =--
=== /ABCI Log ===
https://www.screencast.com/t/6KhJ6LMa90B

Following this document : https://cosmos.network/docs/validators/validator-setup.html#running-a-validator-node

**Comment by rigelrozanski** [comment]
Please open this error as a bug report in Cosmos-SDK 
https://github.com/cosmos/cosmos-sdk/issues/new?template=bug-report.md
