### ISSUE TITLE
Can't change ring!

### ISSUE THREAD

**Issue by dagobertdu94** [cosmos/cosmos#99]
1>------ Erstellen gestartet: Projekt: DuckOS, Konfiguration: Debug Any CPU ------
1>DuckOS -> C:\Users\Alexander\source\repos\DuckOS\DuckOS\bin\Debug\netstandard1.5\DuckOS.dll
2>------ Erstellen gestartet: Projekt: DuckOSBoot, Konfiguration: Debug x86 ------
2>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Alexander\source\repos\DuckOS\DuckOS\bin\Debug\net462\DuckOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.HAL.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Alexander\source\repos\DuckOS\DuckOS\bin\Debug\netstandard1.5\DuckOS.dll" 
2>C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(39,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Alexander\source\repos\DuckOS\DuckOS\bin\Debug\net462\DuckOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.HAL.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.dll" "References:C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Alexander\source\repos\DuckOS\DuckOS\bin\Debug\netstandard1.5\DuckOS.dll" 
2>	Working directory = 'C:\Users\Alexander\source\repos\DuckOS\DuckOS\bin\Debug\net462\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : StackCorruptionDetectionLevel
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Loaded : AdditionalSearchDirs
2>	Loaded : AdditionalReferences
2>	Executing IL2CPU on assembly
2>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_INFO'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_MAPPING'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.MethodIlOp'
2>	Rings: Start check
2>	Rings: Assembly 'Cosmos.System'
2>	Rings:         Ring = System
2>	Rings:     Dependency 'Cosmos.HAL'
2>	Rings:         Ring = HAL
2>	Rings: Assembly 'Cosmos.Core.Common'
2>	Rings:         Ring = Core
2>	Rings: Assembly 'DuckOS'
2>	Rings:         Ring = User
2>	Rings:     Dependency 'Cosmos.System'
2>	Rings:         Ring = System
2>	Rings:     Dependency 'Cosmos.HAL'
2>	Rings:         Ring = HAL
2>	Detecting fields for type 'Cosmos.Debug.Symbols.AssemblyFile'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.Document'
2>	Detecting fields for type 'Cosmos.Debug.Symbols.Method'
2>	Error: Exception: System.Exception: Assembly 'DuckOS' is in ring User(3). It references assembly 'Cosmos.HAL' which is in ring HAL(1), but this is not allowed!
2>	   at Cosmos.IL2CPU.AppAssemblerRingsCheck.Execute(ILScanner scanner, Assembly entryAssembly) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\AppAssemblerRingsCheck.cs:line 105
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 199
2>	Loaded assemblies: 
2>	C:\Users\Alexander\source\repos\DuckOS\DuckOS\bin\Debug\net462\Cosmos.Core.Plugs.Asm.dll
2>	C:\Users\Alexander\source\repos\DuckOS\DuckOS\bin\Debug\net462\Cosmos.Core.Plugs.dll
2>	C:\Users\Alexander\source\repos\DuckOS\DuckOS\bin\Debug\net462\Cosmos.Debug.Kernel.Plugs.Asm.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
2>	C:\Users\Alexander\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>	C:\Users\Alexander\source\repos\DuckOS\DuckOS\bin\Debug\net462\Cosmos.System.Plugs.dll
2>	C:\Users\Alexander\source\repos\DuckOS\DuckOS\bin\Debug\net462\DuckOS.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:12.1252890
2>Die Erstellung des Projekts "DuckOSBoot.Cosmos" ist abgeschlossen -- FEHLER.
2>
========== Erstellen: 1 erfolgreich, 1 fehlerhaft, 0 aktuell, 0 übersprungen ==========

I get this error everytime I try to build my project. But I tried to change this ring thing but it doesn't work.

This is my Kernel.cs:

using Cosmos.Common;
using Cosmos.HAL;
using System;
using System.Collections.Generic;
using System.Text;
using Sys = Cosmos.System;
**[assembly: Ring(Ring.System)]**

namespace ExampleOS
{
    public class Kernel: Sys.Kernel
    {

        protected override void BeforeRun()
        {
            // Any code here
        }
        
        protected override void Run()
        {
            // Any code here
        }
    }
}

I don't know how to set this ring. Please help me!

**Comment by cwgoes** [comment]
I'm afraid you've got the wrong project - likely you want https://github.com/CosmosOS/Cosmos.

**Comment by dagobertdu94** [comment]
I don't know what I have to do with that but if I run "userkit installer.bat" I get this error:

![unbenannt](https://user-images.githubusercontent.com/41807069/43349151-192344a0-91fe-11e8-82c9-f229ec7a3e77.PNG)

**Comment by dagobertdu94** [comment]
But that cosmos, that i use, is working but if i want to use classes from namespace Cosmos.HAL then i can't use that with the user ring and i only want to know how to set this ring to use the namespace Cosmos.HAL.

**Comment by ebuchman** [comment]
Wrong project

**Comment by dagobertdu94** [comment]
If you don't say me something I can't do anything!
